//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalancingSimulation.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BalancingSimulation.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic balancing.
        /// </summary>
        internal static string automaticBalancing {
            get {
                return ResourceManager.GetString("automaticBalancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balancer resistance, Ohm.
        /// </summary>
        internal static string balancerResistance {
            get {
                return ResourceManager.GetString("balancerResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balancing.
        /// </summary>
        internal static string balancing {
            get {
                return ResourceManager.GetString("balancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balancing algorithm.
        /// </summary>
        internal static string balancingAlgorithm {
            get {
                return ResourceManager.GetString("balancingAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balancing curr..
        /// </summary>
        internal static string balancingCurrent {
            get {
                return ResourceManager.GetString("balancingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balancing progress.
        /// </summary>
        internal static string balancingProgress {
            get {
                return ResourceManager.GetString("balancingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Capacity,.
        /// </summary>
        internal static string capacity {
            get {
                return ResourceManager.GetString("capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cell characteristics.
        /// </summary>
        internal static string cellCharacteristics {
            get {
                return ResourceManager.GetString("cellCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cell initial states.
        /// </summary>
        internal static string cellInitialStates {
            get {
                return ResourceManager.GetString("cellInitialStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cell state.
        /// </summary>
        internal static string cellState {
            get {
                return ResourceManager.GetString("cellState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cell voltage, V.
        /// </summary>
        internal static string cellVoltage {
            get {
                return ResourceManager.GetString("cellVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Charge/discharge curr., A.
        /// </summary>
        internal static string chargeCurrent {
            get {
                return ResourceManager.GetString("chargeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Charge level,.
        /// </summary>
        internal static string chargeLevel {
            get {
                return ResourceManager.GetString("chargeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear the history.
        /// </summary>
        internal static string clearHistory {
            get {
                return ResourceManager.GetString("clearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discharge capacity, mAh.
        /// </summary>
        internal static string dischargeCapacity {
            get {
                return ResourceManager.GetString("dischargeCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Energy storage.
        /// </summary>
        internal static string energyStorage {
            get {
                return ResourceManager.GetString("energyStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Imbalance, mAh.
        /// </summary>
        internal static string imbalanceMAh {
            get {
                return ResourceManager.GetString("imbalanceMAh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Imbalance, mV.
        /// </summary>
        internal static string imbalanceMV {
            get {
                return ResourceManager.GetString("imbalanceMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Int. resistance,.
        /// </summary>
        internal static string internalResistance {
            get {
                return ResourceManager.GetString("internalResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leakage curr.,.
        /// </summary>
        internal static string leakageCurrent {
            get {
                return ResourceManager.GetString("leakageCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mA.
        /// </summary>
        internal static string mA {
            get {
                return ResourceManager.GetString("mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mAh.
        /// </summary>
        internal static string mAh {
            get {
                return ResourceManager.GetString("mAh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum.
        /// </summary>
        internal static string maximum {
            get {
                return ResourceManager.GetString("maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of cycles.
        /// </summary>
        internal static string numberOfCycles {
            get {
                return ResourceManager.GetString("numberOfCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simulation.
        /// </summary>
        internal static string simulation {
            get {
                return ResourceManager.GetString("simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simulation speed.
        /// </summary>
        internal static string simulationSpeed {
            get {
                return ResourceManager.GetString("simulationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на uA.
        /// </summary>
        internal static string uA {
            get {
                return ResourceManager.GetString("uA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на uOhm.
        /// </summary>
        internal static string uOhm {
            get {
                return ResourceManager.GetString("uOhm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на usable capacity, mAh.
        /// </summary>
        internal static string usableCapacity {
            get {
                return ResourceManager.GetString("usableCapacity", resourceCulture);
            }
        }
    }
}
